import {
  AwardIcon,
  BellIcon,
  BookOpenIcon,
  CalendarCheckIcon,
  CalendarIcon,
  ChartColumnIcon,
  ClipboardListIcon,
  CreditCardIcon,
  FileTextIcon,
  GraduationCapIcon,
  HouseIcon,
  IdCardIcon,
  MessageSquareTextIcon,
  PencilIcon,
  PrinterIcon,
  SettingsIcon,
  TableIcon,
  UploadIcon,
  UserRoundIcon,
  UsersIcon,
  type LucideIcon,
} from "lucide-react"

// The icons a dashboard menu can show. Legacy took a Font Awesome class
// (fa-users) typed in by hand; the admin uses lucide, so it is picked here.
export const dashboardMenuIcons: Record<string, { label: string; Icon: LucideIcon }> = {
  users: { label: "Users", Icon: UsersIcon },
  user: { label: "User", Icon: UserRoundIcon },
  "graduation-cap": { label: "Graduation cap", Icon: GraduationCapIcon },
  "id-card": { label: "ID card", Icon: IdCardIcon },
  upload: { label: "Upload", Icon: UploadIcon },
  "calendar-check": { label: "Calendar check", Icon: CalendarCheckIcon },
  calendar: { label: "Calendar", Icon: CalendarIcon },
  "clipboard-list": { label: "Clipboard", Icon: ClipboardListIcon },
  pencil: { label: "Pencil", Icon: PencilIcon },
  table: { label: "Table", Icon: TableIcon },
  "file-text": { label: "Document", Icon: FileTextIcon },
  chart: { label: "Chart", Icon: ChartColumnIcon },
  award: { label: "Award", Icon: AwardIcon },
  book: { label: "Book", Icon: BookOpenIcon },
  printer: { label: "Printer", Icon: PrinterIcon },
  message: { label: "Message", Icon: MessageSquareTextIcon },
  bell: { label: "Bell", Icon: BellIcon },
  payment: { label: "Payment", Icon: CreditCardIcon },
  home: { label: "Home", Icon: HouseIcon },
  settings: { label: "Settings", Icon: SettingsIcon },
}
